baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "starter"

[params]
    description = "Meta description goes here"
    images = ["images/metaImage.jpg"]

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "contact"
    name = "Contact Me"
    url = "/contact/"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 30