baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "starter"

[params]
    description = "Meta description goes here"
    images = ["images/metaImage.jpg"]
    logo = "/images/logo-hugo.svg"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20